jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Replace with your AWS region

    - name: Remove existing content from S3 bucket
      run: |
        aws s3 rm s3://nasir-landing-page/ --recursive

    - name: Sync new content to S3 bucket
      run: |
        aws s3 cp --recursive . s3://nasir-landing-page/
